[project]
name = "discordverifybot"
version = "0.1.0"
description = "A Discord verification bot for Railway deployment."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
discord.py = "*"
aiohttp = "*"
python-dotenv = "*" 